Redirect build stdout to file to speed-up builds. Print logs only on failure

diff --git a/.github/actions/build-project/action.yaml b/.github/actions/build-project/action.yaml
--- a/.github/actions/build-project/action.yaml
+++ b/.github/actions/build-project/action.yaml
@@ -109,7 +109,10 @@ runs:
             '1.6.2' \
             "$(config .config // ${DefaultConfig})" \
             "${{ inputs.extra-scalac-options }}" \
-            "${{ inputs.disabled-scalac-options }}" 2>&1 | tee build-logs.txt
+            "${{ inputs.disabled-scalac-options }}" 2>&1 > build-logs.txt
+
+          # Remove ASCII coloring from the indexed logs
+          cat build-logs.txt | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" > build-logs-uncolored.txt 
 
           /build/feed-elastic.sh \
             'https://scala3.westeurope.cloudapp.azure.com/data' \
@@ -117,7 +120,7 @@ runs:
             "$(cat build-status.txt)" \
             "$(date --iso-8601=seconds)" \
             build-summary.txt \
-            build-logs.txt \
+            build-logs-uncolored.txt \
             "$(config .version)" \
             "${{ inputs.scala-version }}" \
             "${{ github.run_id }}" \
@@ -143,4 +146,10 @@ runs:
       if: steps.check-history.outputs.can-skip-build != 'true'
       run: |
         # Set the result of the build
-        [ "$(cat build-status.txt)" = "success" ]
+        if [[ "$(cat build-status.txt)" == "success" ]]; then 
+          echo "Build successful"
+        else 
+          echo "Build failure: "
+          cat -n ${{ github.workspace }}/build-logs.txt
+          exit 1
+        fi
